[General]
TcpServerPort=0
ReportStats=true
DebugLogLevel=info
# DebugLogLevel=trace


[UartEndpoint ELRS]
Mode=Server
Device=/dev/ttyUSB0
Baud=460800

[UdpEndpoint QGC]
Mode=Server
Address=0.0.0.0
Port=14550
BlockMsgIdIn=69,110

[UdpEndpoint DockerIn]
Mode=Normal
Address=172.17.0.2
Port=14541
